# Generated by Django 5.0.2 on 2024-03-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('number', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('carname', models.CharField(max_length=10, null=True)),
                ('carissue', models.CharField(max_length=10, null=True)),
                ('service', models.CharField(max_length=10, null=True)),
                ('bill', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
