# Generated by Django 5.0.2 on 2024-03-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbltechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicianname', models.CharField(max_length=10, null=True)),
                ('staffnumber', models.IntegerField(null=True)),
                ('staffexperience', models.CharField(max_length=10, null=True)),
                ('staffdutytime', models.CharField(max_length=10, null=True)),
                ('staffcode', models.CharField(max_length=10, null=True)),
                ('staffamount', models.CharField(max_length=10, null=True)),
                ('zip', models.IntegerField(null=True)),
            ],
        ),
    ]
