# Generated by Django 5.0.2 on 2024-03-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m5', '0002_tbltechnician'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('number', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('carname', models.CharField(max_length=10, null=True)),
                ('carissue', models.CharField(max_length=10, null=True)),
                ('service', models.CharField(max_length=10, null=True)),
                ('bill', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tblservice',
            old_name='address',
            new_name='carservicename',
        ),
        migrations.RenameField(
            model_name='tblservice',
            old_name='bill',
            new_name='serviceamount',
        ),
        migrations.RenameField(
            model_name='tblservice',
            old_name='carissue',
            new_name='servicedescription',
        ),
        migrations.RenameField(
            model_name='tblservice',
            old_name='carname',
            new_name='servicedetails',
        ),
        migrations.RenameField(
            model_name='tblservice',
            old_name='name',
            new_name='servicetime',
        ),
        migrations.RemoveField(
            model_name='tblservice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='tblservice',
            name='service',
        ),
    ]
